export default {
	userAddress:state=>state.userAddress,
	tabselect: state => state.tabselect,
	onActive:state=>state.onActive,
	busActive:state=>state.busActive,
  ordersn: state => state.ordersn,
  myOrders:state => state.myOrders,
  searchnum: state => state.searchnum,
  reason: state => state.reason,
  backtime:state =>state.backtime,
  descri:state =>state.descri,
  refundid:state=>state.refundid,
  backprice:state=>state.backprice,
  oldaddress:state=>state.oldaddress,
  isConfirm:state=>state.isConfirm,
  isNull:state=>state.isNull,
  defaultAddressIsNull:state=>state.defaultAddressIsNull,
  isScroll:state=>state.isScroll,
  addtype:state=>state.addtype,
  haslogo:state=>state.haslogo,
  changeAddress:state=>state.changeAddress,
  changeDelivery:state=>state.changeDelivery,
  changeDeliveryIndex:state=>state.changeDeliveryIndex,
  tabbarIsSHow:state=>state.tabbarIsSHow,
  orderStatus:state=>state.orderStatus,
  isCollection:state=>state.isCollection
}

